In [18]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta, date
from scipy.spatial.distance import squareform, pdist
import os
import geopy
from geopy import distance

In [3]:
 # adjacency matrix
landLocation = pd.read_csv(
    "../disneyenv/disneyenv/envs/data/landLocation.csv")
walking_speed = 0.0804672  # km/min

squareform(pdist(landLocation[[
                "longitude", "latitude"]], lambda u, v: geopy.distance.geodesic(u, v).km/walking_speed))

array([[ 0.        ,  6.29793434,  7.59231886,  6.72144458,  8.47547891,
        10.8398949 ,  9.23438658,  4.42746857,  6.43210074, 15.27367324,
         8.4711075 ,  4.43150511,  6.98223266,  4.08052913,  3.20920805,
         1.91928679,  7.98649939],
       [ 6.29793434,  0.        ,  3.94487915, 11.69862874,  2.84048225,
         4.77305836,  6.72184337,  3.14041845,  3.32758393,  9.0552489 ,
        11.72166912,  8.54145473,  5.30475721,  9.51972268,  9.20627751,
         6.30880917,  5.73553632],
       [ 7.59231886,  3.94487915,  0.        , 10.70657401,  2.52043328,
         4.64300916,  2.78603503,  3.18602785,  1.16637167,  8.91580397,
         9.56140851,  7.58226124,  2.05302365,  9.25782968,  9.53521785,
         6.53538017,  1.96524785],
       [ 6.72144458, 11.69862874, 10.70657401,  0.        , 12.7501009 ,
        15.18102084, 10.55716871,  8.6827938 ,  9.90069096, 19.59417004,
         3.57220657,  3.20754645,  8.91760654,  2.66572014,  3.91595377,
         5.57229488

In [5]:
df = pd.read_csv("../disneyenv/disneyenv/envs/data/disneyRideTimes.csv")
df2 = pd.read_csv("../disneyenv/disneyenv/envs/data/hourlyWeather.csv")

/tmp/ipykernel_115947/1302428089.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../disneyenv/disneyenv/envs/data/disneyRideTimes.csv")


In [17]:
df[df.rideID == 18755618].waitMins.value_counts()

Series([], Name: waitMins, dtype: int64)

In [12]:
df.waitMins.max()

900.0

In [11]:
df2.feelsLikeF.max()

115

In [13]:
ridesinfo = pd.read_csv(
            "../disneyenv/disneyenv/envs/data/rideDuration.csv")
rides = ridesinfo["id"].unique()

In [119]:
df2["dateTime"] = pd.to_datetime(df2["dateTime"])
df2["date"] = df2["dateTime"].dt.date
df2 = df2.set_index("dateTime").sort_index()

In [9]:
df["dateTime"] = pd.to_datetime(df["dateTime"])
df["date"] = df["dateTime"].dt.date
df = df.set_index(["rideID", "dateTime"]).sort_index()

In [37]:
sample_ts = datetime.strptime("2018-03-11 08:41:21.330527", "%Y-%m-%d %H:%M:%S.%f")
target_df = df[df["date"] == sample_ts.date()]
input_waitTime_index = pd.MultiIndex.from_arrays(
            [np.array(rides), np.repeat(sample_ts, len(rides))])

KeyError: 'date'

In [45]:
(sample_ts - datetime.combine(sample_ts.date(),
                               datetime.min.time())).total_seconds()

31281.330527

In [44]:
((sample_ts - datetime.combine(sample_ts.date(),
                               datetime.min.time())).total_seconds() - 28800) / 50400

0.04923274855158727

In [69]:
target_ilocs = target_df.index.get_indexer(input_waitTime_index, method="ffill")
valid_targets = np.where(target_ilocs != -1)[0]

In [70]:
valid_targets = valid_targets[
                target_df.index[target_ilocs[valid_targets]].get_level_values(
                    0) == input_waitTime_index[valid_targets].get_level_values(0)]

In [71]:
waitTime = np.repeat(np.nan, len(input_waitTime_index))

In [72]:
waitTime[valid_targets] = target_df.iloc[target_ilocs[valid_targets]
                                                     ].waitMins.values

In [73]:
waitTime = np.nan_to_num(waitTime)

In [74]:
waitTime

array([ 0.,  5.,  0., 15.,  5.,  0.,  0.,  0.,  0.,  5.,  5.,  5.,  0.,
        0., 10.,  5.,  0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,
        0.,  5.,  0.,  5.,  0., 10.,  0., 30.,  5.,  0.,  5.,  5.,  0.,
        5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 15.,
        0.,  0.,  0.,  5.,  5.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  5.,  5.,  5.,  0.,  0.,  0., 10.,  5.,  0.,
        0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0., 15.,  0.,  0.,  0.,
        0.,  0.])

In [75]:
operationStatus = np.repeat(0, len(input_waitTime_index))
operationStatus[valid_targets] = (
    target_df.iloc[target_ilocs[valid_targets]].status == "Operating")

In [76]:
operationStatus

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [35]:
target_df.index[valid_targets]

MultiIndex([(353289, '2018-07-24 00:00:14'),
            (353289, '2018-07-24 00:30:05'),
            (353289, '2018-07-24 01:00:15'),
            (353289, '2018-07-24 01:30:04'),
            (353289, '2018-07-24 02:00:14'),
            (353289, '2018-07-24 02:30:05'),
            (353289, '2018-07-24 03:00:15'),
            (353289, '2018-07-24 03:30:05'),
            (353289, '2018-07-24 04:00:15'),
            (353289, '2018-07-24 04:30:04'),
            ...
            (353293, '2018-07-24 00:00:14'),
            (353293, '2018-07-24 00:30:05'),
            (353293, '2018-07-24 01:00:15'),
            (353293, '2018-07-24 01:30:04'),
            (353293, '2018-07-24 02:00:14'),
            (353293, '2018-07-24 02:30:05'),
            (353293, '2018-07-24 03:00:15'),
            (353293, '2018-07-24 03:30:05'),
            (353293, '2018-07-24 04:00:15'),
            (353293, '2018-07-24 04:30:04')],
           names=['rideID', 'dateTime'], length=106)

In [33]:
input_waitTime_index[valid_targets].get_level_values(0)

UInt64Index([  353289,   353387,   353433,   353451,   353457, 17328049,
             18766536, 18774860, 18946452,   353291,
             ...
             18752875, 18752877, 18848246, 18848247, 16581435, 17328050,
             18426726, 18532806, 18693648, 18755618],
            dtype='uint64', length=106)

In [30]:
valid_targets

array([0])

In [113]:
m2 = m.values
m2[0] = np.nan

m2

array([nan, (18946452, Timestamp('2016-08-24 04:40:05'))], dtype=object)

In [136]:
df[df.status == "Operating"]["waitMins"].unique()

array([ nan,   5.,  45.,  35.,  30.,  40.,  15.,  25.,  20.,  10.,  50.,
        60.,  65.,  55.,  70., 105.,  85.,  95.,  75.,  80.,  90.,   0.,
       115., 100., 125., 120., 150., 500., 145., 140., 240., 110., 200.,
       185., 180., 130., 175., 165.,  13., 190., 160., 135., 210., 170.,
       195., 280., 205., 215., 155., 250., 900., 750.])

In [128]:
df[df.date == exdt]["status"].value_counts()

Closed                 2812
Operating              2109
Down                    137
Operates Seasonally     102
Opening Soon             32
Extra Magic Hours         2
Name: status, dtype: int64

In [104]:
df.index.get_indexer(m, method="ffill")

array([2400936])

In [91]:
sample_ts = sample_ts - timedelta(days=365)

In [26]:
ridesinfo[ridesinfo['duration_min'].isna()]

id  parkID                                           name  \
54    353329  330339  Fire Engine, presented by National Car Rental   
91  18249927  330339                        Haunted Mansion Holiday   

                   land  height  duration_min popularity  landID  
54  Main Street, U.S.A.     NaN           NaN        NaN       7  
91   New Orleans Square     NaN           NaN        NaN      12

In [19]:
ridesinfo = pd.read_csv("../disneyenv/disneyenv/envs/data/rideDuration.csv")

In [68]:
current_date = np.random.choice(avail_dates)

In [70]:
current_date.year

2018

In [51]:
rides = ridesinfo["id"].unique()

In [52]:
np.append(np.arange(len(rides)), -1)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105,  -1])

In [44]:
from scipy.spatial.distance import squareform, pdist
import geopy.distance

In [34]:
landLocation = pd.read_csv("../disneyenv/disneyenv/envs/data/landLocation.csv")

In [42]:
walking_speed = 0.0804672

In [28]:
df["dateTime"] = pd.to_datetime(df["dateTime"])

In [29]:
df["date"] = df["dateTime"].dt.date

In [53]:
avail_dates = df["date"].unique()

In [183]:
exdt = datetime.strptime("2017-09-11", "%Y-%m-%d").date()


In [31]:
arr = np.load("../disneyenv/disneyenv/envs/data/walking_time.npy")

In [43]:
df[(df["status"] == "Operating") & (~(df["waitMins"].isna()))]

rideID             dateTime  waitMins fastPassTime     status  \
22544      353291  2017-05-22 09:30:07       5.0          NaN  Operating   
22545      353291  2017-05-22 10:30:15      45.0          NaN  Operating   
22546      353291  2017-05-22 11:30:15      35.0          NaN  Operating   
22547      353291  2017-05-22 12:30:15      30.0          NaN  Operating   
22548      353291  2017-05-22 13:30:06      45.0          NaN  Operating   
...           ...                  ...       ...          ...        ...   
2354379  18774860  2017-10-31 19:00:12      75.0          NaN  Operating   
2354380  18774860  2017-10-31 19:30:05      75.0          NaN  Operating   
2354381  18774860  2017-10-31 20:00:12      55.0          NaN  Operating   
2354382  18774860  2017-10-31 20:30:04      55.0          NaN  Operating   
2354383  18774860  2017-10-31 21:00:12      55.0          NaN  Operating   

               date  
22544    2017-05-22  
22545    2017-05-22  
22546    2017-05-22  
22547    2017-05-22  
22548    2017-05-22  
...             ...  
2354379  2017-10-31  
2354380  2017-10-31  
2354381  2017-10-31  
2354382  2017-10-31  
2354383  2017-10-31  

[668748 rows x 6 columns]

In [51]:
open_df.groupby("date")["rideID"].nunique().sort_values()

date
2017-09-06    52
2017-08-30    53
2017-09-10    53
2017-09-09    53
2017-09-08    53
              ..
2017-08-11    91
2017-08-07    91
2017-08-08    91
2017-08-10    91
2017-08-06    91
Name: rideID, Length: 482, dtype: int64