In [174]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta, date
from scipy.spatial.distance import squareform, pdist

In [141]:
import os
from geopy import distance
os.getcwd()

'/gpfs/data/oermannlab/users/hz2212/DS-GA 3001-007/notebooks'

In [153]:
 # adjacency matrix
landLocation = pd.read_csv(
    "../disneyenv/disneyenv/envs/data/landLocation.csv")
walking_speed = 0.0804672  # km/min

np.max(squareform(pdist(landLocation[[
                                   "longitude", "latitude"]], lambda u, v: geopy.distance.geodesic(u, v).km/walking_speed)))

19.59417004116794

In [145]:
df.index.get_level_values(0).unique()

Int64Index([  353289,   353291,   353293,   353295,   353301,   353303,
              353305,   353309,   353311,   353313,
            ...
            18741420, 18752875, 18752877, 18755618, 18766536, 18766537,
            18774860, 18848246, 18848247, 18946452],
           dtype='int64', name='rideID', length=110)

In [82]:
df = pd.read_csv("../disneyenv/disneyenv/envs/data/disneyRideTimes.csv")

/tmp/ipykernel_26196/2545870254.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../disneyenv/disneyenv/envs/data/disneyRideTimes.csv")


In [116]:
df2 = pd.read_csv("../disneyenv/disneyenv/envs/data/hourlyWeather.csv")

In [119]:
df2["dateTime"] = pd.to_datetime(df2["dateTime"])
df2["date"] = df2["dateTime"].dt.date
df2 = df2.set_index("dateTime").sort_index()

In [83]:
df["dateTime"] = pd.to_datetime(df["dateTime"])
df["date"] = df["dateTime"].dt.date
df = df.set_index(["rideID", "dateTime"]).sort_index()

In [156]:
df2["rainStatus"].unique()

array([ 0,  5,  6, 14, 10,  2])

In [154]:
df2.describe()

resortID    rainStatus    feelsLikeF
count     11585.0  11585.000000  11585.000000
mean   80008297.0      1.524126     68.079327
std           0.0      1.473977     10.186385
min    80008297.0      0.000000     41.000000
25%    80008297.0      0.000000     61.000000
50%    80008297.0      2.000000     68.000000
75%    80008297.0      2.000000     74.000000
max    80008297.0     14.000000    115.000000

In [77]:
df.iloc[4528]

waitMins               NaN
fastPassTime           NaN
status              Closed
date            2017-08-24
Name: (2017-08-24 04:30:05, 353289), dtype: object

In [157]:
from gym.spaces import Box, Discrete, Dict
o = Dict({"position": Box(-1, 1, shape=(1,)), "color": Discrete(3)}).sample()

In [151]:
landLocation

name  longitude    latitude  landID
0        Hollywood Land  33.807787 -117.917199       0
1          Tomorrowland  33.812353 -117.917015       1
2          Frontierland  33.812588 -117.920432       2
3            Pixar Pier  33.804921 -117.921925       3
4           Fantasyland  33.813791 -117.918783       4
5     Mickey's Toontown  33.815569 -117.918553       5
6       Critter Country  33.812541 -117.922853       6
7   Main Street, U.S.A.  33.810680 -117.918868       7
8         Adventureland  33.811893 -117.919854       8
9          a bug's land  33.818824 -117.918374       9
10        Paradise Pier  33.806491 -117.924395      10
11         Grizzly Peak  33.807105 -117.920962      11
12   New Orleans Square  33.811380 -117.921476      12
13        Pacific Wharf  33.805886 -117.919917      13
14            Cars Land  33.805824 -117.918698      14
15   Buena Vista Street  33.808037 -117.918839      15
16    Disneyland Resort  33.811986 -117.921981      16

In [105]:
m = pd.MultiIndex.from_arrays([[18946452, 18946452], [sample_ts, sample_ts]])

In [113]:
m2 = m.values
m2[0] = np.nan

m2

array([nan, (18946452, Timestamp('2016-08-24 04:40:05'))], dtype=object)

In [114]:
bool(np.array([]))

/tmp/ipykernel_26196/766069897.py:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  bool(np.array([]))


False

In [125]:
exdt

datetime.date(2017, 8, 24)

In [136]:
df[df.status == "Operating"]["waitMins"].unique()

array([ nan,   5.,  45.,  35.,  30.,  40.,  15.,  25.,  20.,  10.,  50.,
        60.,  65.,  55.,  70., 105.,  85.,  95.,  75.,  80.,  90.,   0.,
       115., 100., 125., 120., 150., 500., 145., 140., 240., 110., 200.,
       185., 180., 130., 175., 165.,  13., 190., 160., 135., 210., 170.,
       195., 280., 205., 215., 155., 250., 900., 750.])

In [128]:
df[df.date == exdt]["status"].value_counts()

Closed                 2812
Operating              2109
Down                    137
Operates Seasonally     102
Opening Soon             32
Extra Magic Hours         2
Name: status, dtype: int64

In [104]:
df.index.get_indexer(m, method="ffill")

array([2400936])

In [91]:
sample_ts = sample_ts - timedelta(days=365)

In [31]:
exdt = df["dateTime"].dt.date[100000]


In [42]:
sample_ts = ride_date_df.dateTime.iloc[10] + timedelta(minutes=10)
sample_ts

Timestamp('2017-08-24 04:40:05')

In [59]:
ridesinfo = pd.read_csv("../disneyenv/disneyenv/envs/data/rideDuration.csv")

In [68]:
current_date = np.random.choice(avail_dates)

In [70]:
current_date.year

2018

In [51]:
rides = ridesinfo["id"].unique()

In [52]:
np.append(np.arange(len(rides)), -1)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105,  -1])

In [44]:
from scipy.spatial.distance import squareform, pdist
import geopy.distance

In [34]:
landLocation = pd.read_csv("../disneyenv/disneyenv/envs/data/landLocation.csv")

In [42]:
walking_speed = 0.0804672

In [28]:
df["dateTime"] = pd.to_datetime(df["dateTime"])

In [29]:
df["date"] = df["dateTime"].dt.date

In [53]:
avail_dates = df["date"].unique()

In [183]:
exdt = datetime.strptime("2017-09-11", "%Y-%m-%d").date()


In [184]:
df[df["date"] == exdt].waitMins.value_counts()

5.0      361
10.0     234
15.0     168
20.0      97
30.0      84
25.0      71
45.0      56
35.0      56
40.0      38
60.0      14
90.0      10
0.0       10
65.0      10
55.0       9
75.0       5
50.0       4
70.0       2
80.0       2
120.0      1
Name: waitMins, dtype: int64

In [43]:
df[(df["status"] == "Operating") & (~(df["waitMins"].isna()))]

rideID             dateTime  waitMins fastPassTime     status  \
22544      353291  2017-05-22 09:30:07       5.0          NaN  Operating   
22545      353291  2017-05-22 10:30:15      45.0          NaN  Operating   
22546      353291  2017-05-22 11:30:15      35.0          NaN  Operating   
22547      353291  2017-05-22 12:30:15      30.0          NaN  Operating   
22548      353291  2017-05-22 13:30:06      45.0          NaN  Operating   
...           ...                  ...       ...          ...        ...   
2354379  18774860  2017-10-31 19:00:12      75.0          NaN  Operating   
2354380  18774860  2017-10-31 19:30:05      75.0          NaN  Operating   
2354381  18774860  2017-10-31 20:00:12      55.0          NaN  Operating   
2354382  18774860  2017-10-31 20:30:04      55.0          NaN  Operating   
2354383  18774860  2017-10-31 21:00:12      55.0          NaN  Operating   

               date  
22544    2017-05-22  
22545    2017-05-22  
22546    2017-05-22  
22547    2017-05-22  
22548    2017-05-22  
...             ...  
2354379  2017-10-31  
2354380  2017-10-31  
2354381  2017-10-31  
2354382  2017-10-31  
2354383  2017-10-31  

[668748 rows x 6 columns]

In [51]:
open_df.groupby("date")["rideID"].nunique().sort_values()

date
2017-09-06    52
2017-08-30    53
2017-09-10    53
2017-09-09    53
2017-09-08    53
              ..
2017-08-11    91
2017-08-07    91
2017-08-08    91
2017-08-10    91
2017-08-06    91
Name: rideID, Length: 482, dtype: int64